from typing import Protocol

from main.domain.models import ImagePromptContext


class VisionDescriber(Protocol):
    async def analyze_character(self, image: bytes) -> dict: ...
    async def describe_face(self, image: bytes) -> str: ...
    async def analyze_pose_orientation(self, image: bytes) -> dict: ...


class ChatResponder(Protocol):
    async def chat(self, prompt: str) -> str: ...


class PromptEnhancer(Protocol):
    async def enhance_image_prompt(self, context: ImagePromptContext) -> str: ...
    async def translate_video_prompt(self, prompt: str, image: bytes | None = None) -> str: ...
